FE_3week/accounts/urls.py
from django.urls import path
from .views import login, logout, signup

app_name = 'accounts'
urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('signup/', signup, name='signup'),
]

FE_3week/main/urls.py
# main의 urls.py 작성
from django.urls import path
from django.contrib import admin
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('product/<int:product_id>/', views.product_detail, name="product_detail"),
    path('product/<int:product_id>/create_comment/', views.create_comment, name="create_comment"),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name="delete_comment"),
]

FE_3week/project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
]

FE_3week/accounts/models.py
from django.db import models

# Create your models here.

FE_3week/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    id                =   models.AutoField(primary_key=True)
    name              =   models.CharField(max_length=50)
    description       =   models.CharField(max_length=50)
    origin_price      =   models.IntegerField()
    discount_price    =   models.IntegerField()
    discount_rate     =   models.IntegerField()
    category          =   models.ManyToManyField('Category')
    notice            =   models.CharField(max_length=200)
    image_url         =   models.URLField(max_length=2000)

    def summary(self):
        return self.description[:20]
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table    = 'products'

class Category(models.Model):
    name            =   models.CharField(max_length=45)

    def __str__(self):
        return self.name
    class Meta:
        db_table    = 'categories'

class ProductComment(models.Model):
    id              = models.AutoField(primary_key=True)
    user            = models.ForeignKey(User, on_delete=models.CASCADE)
    product         = models.ForeignKey('Product', on_delete=models.CASCADE)
    star            = models.IntegerField()
    content         = models.TextField()
    created_at      = models.DateTimeField(auto_now=True)

    class Meta:
        db_table    = 'product_comments'

FE_3week/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib.auth.models import User

# Create your views here.
def login_page(request):
    return render(request, 'accounts/login.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')
        else:
            return render(request, 'accounts/login.html', {'error': '아이디나 비밀번호가 틀렸습니다. 다시 입력해주세요.'})
    else:
        return render(request, 'accounts/login.html', {'error': '로그인 실패'})
    

def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']

        # username 미입력시 에러
        if not username:
            return render(request, 'accounts/signup.html', {'error': '닉네임을 입력해주세요.'})
        
        # 비밀번호에 영문 대소문자, 숫자, 특수문자 (@ ! ? - _)가 각각 1개 이상 포함되어야 하며 8자 이상이어야 함
        if not (any(c.isupper() for c in password) and any(c.islower() for c in password) and any(c.isdigit() for c in password) and any(c in '@!?-_' for c in password) and len(password) >= 8):
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 조건에 맞지 않습니다. 다시 입력해주세요.'})

        if password == password2:
            if User.objects.filter(username=username).exists():
                return render(request, 'accounts/signup.html', {'error': '이미 사용중인 닉네임입니다.'})
            else:
                user = User.objects.create_user(username=username, password=password)
                auth.login(request, user)
                return redirect('main:mainpage')
        else:
            return render(request, 'accounts/signup.html', {'error': '비밀번호가 일치하지 않습니다.'})
    else:
        return render(request, 'accounts/signup.html')

FE_3week/main/views.py
from django.shortcuts import render, redirect
from .models import Product, ProductComment

# Create your views here.
# 메인페이지와 메인페이지의 products 정보들을 불러오는 함수
def mainpage(request):
    products = Product.objects.all()
    return render(request, 'main/mainpage.html', {'products': products})

# 상품의 상세페이지를 불러오는 함수
def product_detail(request, product_id):
    product = Product.objects.get(id=product_id)
    comments = product.productcomment_set.all()
    return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments})

# 상품의 상세페이지에서 댓글을 작성하는 함수
def create_comment(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        star = request.POST['star']
        content = request.POST['content']
        product.productcomment_set.create(star=star, content=content, user_id=request.user.id)
    return redirect('main:product_detail', product_id)

# 상품의 상세페이지에서 댓글을 삭제하는 함수 (단, 댓글 작성자만 삭제 가능)
def delete_comment(request, comment_id):
    comment = ProductComment.objects.get(id=comment_id)
    product = comment.product
    if request.user.id != comment.user_id:
        comments = product.productcomment_set.all()
        return render(request, 'main/product_detail_page.html', {'product': product, 'comments': comments, 'error': '본인의 댓글만 삭제할 수 있습니다.'})
    comment.delete()
    return redirect('main:product_detail', product.id)

FE_3week/accounts/templates/accounts/login.html
<!-- 임시 로그인 페이지 -->
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/login.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="Body">
      <form class="loginview" action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        <p class="login_ko">로그인</p>
        <div class="input_list">
          <div class="login_input">
            <input type="text" class="login_input_textarea B2" placeholder="아이디를 입력해주세요" name="username" id="username" required>
          </div>
          <div class="login_input">
            <input type="password" class="login_input_textarea B2" placeholder="비밀번호를 입력해주세요" name="password" id="password" required>
          </div>
        </div>
        <div class="find"> <!-- 추후 추가 찾기부분 -->
          <a class="Caption font-font1" href="/">아이디 찾기</a>
          <p class="Caption font-font1">|</p>
          <a class="Caption font-font1" href="/">비밀번호 찾기</a>
        </div>
        <div class="btn_list">
          <div class="login_btn" id="login_btn">
            <button type="submit" style="color: #999;" class="Btn" id="login_input_btn" disabled>로그인</button>
          </div>
          <div class="signup_btn" id="signup_btn">
            <a href="/accounts/signup/" style="color: #5E0080;" class="Btn">회원가입</a>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const id = document.getElementById("username");
    const pw = document.getElementById("password");
    const login_btn = document.getElementById("login_input_btn");
    const login_btn_color = document.getElementById("login_btn");

    id.addEventListener("input", (event) => {
      if (id.value.trim().length > 0) {
        login_btn_update();
      }
    });

    pw.addEventListener("input", (event) => {
      if (pw.value.trim().length > 0) {
        login_btn_update();
      }
    });

    const login_btn_update = () => {
      if (id.value.trim().length > 0 && pw.value.trim().length > 0){
        login_btn.disabled = false;
        login_btn_color.style.backgroundColor = "#5E0080";
        login_btn.style.color = "#fff";
      }
      else {
        login_btn.disabled = true;
        login_btn_color.style.backgroundColor = "#E2E2E2";
        login_btn.style.color = "#999";
      }
    }
  });
</script>

{% endblock %}

FE_3week/accounts/templates/accounts/signup.html
<!-- 임시 회원가입 페이지 -->
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/accounts/signup.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="Body">
      <form class="signupview" action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        <p class="signup_ko">회원가입</p>
        <hr class="hr_1">
        <div class="input_list">
          <div class="signup_input">
            <p class="signup_text B2-bold text-black">아이디</p>
            <div class="signup_input_id">
              <input type="text" class="signup_input_textarea B2" placeholder="아이디를 입력해주세요" name="username" id="username" required>
            </div>
          </div>
          <div class="signup_input">
            <p class="signup_text B2-bold text-black">비밀번호</p>
            <div class="signup_input_password">
              <input type="password" class="signup_input_textarea B2" placeholder="비밀번호를 입력해주세요" name="password" id="password" required>
              <ul class="font1">
                <li>⋅ 비밀번호를 8자 이상으로 작성해주세요.</li>
                <li>⋅ 영문 대소문자, 숫자, 특수문자를 하나 이상포함해주세요.</li>
                <li>⋅ 사용가능 특수문자 @!?-_</li>
              </ul>
            </div>
          </div>
          <div class="signup_input">
            <p class="signup_text B2-bold text-black">비밀번호 확인</p>
            <div class="signup_input_password">
              <input type="password" class="signup_input_textarea B2" placeholder="비밀번호를 한번 더 입력해주세요" name="password2" id="password2" required>
              <p class="text-red Caption" id="password_not_right">비밀번호가 일치하지 않습니다!</p>
            </div>
          </div>
        </div>
        <hr class="hr_2">
          <div class="signup_btn" id="signup_btn">
            <button type="submit" class="signup_input_btn font-font2 Btn" id="signup_input_btn" disabled>가입하기</button>
          </div>
      </form>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const id = document.getElementById("username");
    const pw1 = document.getElementById("password");
    const pw2 = document.getElementById("password2");
    const sign_btn = document.getElementById("signup_input_btn");
    const sign_btn_color = document.getElementById("signup_btn");
    const password_not_right = document.getElementById("password_not_right");
    
    var passwordRegex = /^(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9])(?=.*?[@!?_-]).{8,}$/;

    id.addEventListener("input", (event) => {
      if (id.value.trim().length > 0) {
        sign_btn_update();
      }
    });

    pw1.addEventListener("input", (event) => {
      if (pw1.value.trim().length > 0) {
        sign_btn_update();
      }
    });

    pw2.addEventListener("input", (event) => {
      if (pw2.value.trim().length > 0) {
        sign_btn_update();
      }
    });

    const sign_btn_update = () => { // 비밀번호가 같은 상태에서 아이디를 지웠을 때 false로 변하지 않는 문제 발견.
      if (id.value.trim().length > 0 && pw1.value == pw2.value && passwordRegex.test(pw1.value) == true){
        sign_btn.disabled = false;
        sign_btn_color.style.backgroundColor = "#5E0080";
        sign_btn.style.color = "#fff"
        password_not_right.style.display = "none";
        
      } // 비밀번호 같고 길이도 길고 조건도 충족
      else if (pw1.value == pw2.value){
        sign_btn.disabled = true;
        sign_btn_color.style.backgroundColor = "#E2E2E2";
        sign_btn.style.color = "#999";
        password_not_right.style.display = "none";
      }
      else {
        sign_btn.disabled = true;
        sign_btn_color.style.backgroundColor = "#E2E2E2";
        sign_btn.style.color = "#999";
        password_not_right.style.display = "";
      }
    }
  });
</script>

{% endblock %}

FE_3week/main/templates/main/mainpage.html
{% extends 'base.html' %} {% block content %} {% load static %}
<!-- css 파일 -->
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/main_page.css'%}"
/>


<div class="screen">
  <div class="main text-white">
    <div class="tag text-font1">
      <div class="tag2 T1" id="tag2">
        <a href="/">인기신상랭킹</a>
        <a>입점특가</a>
        <a>간편한끼</a>
        <a>요즘간식</a>
        <a>주방﹒리빙</a>
        <a>뷰티</a>
        <a>패션﹒잡화</a>
      </div>
    </div>
  
    <div class="body">
      <div class="category_navbar">
        <div class="head">
          <a class="text-font1 H3">필터</a>
          <button class="reset_btn text-font3" id="reset_btn">
            <a class="reset_btn_2" id="reset_btn_2">
              <img class="icon-20 icon-color-1" src="{% static 'assets/icons/reset.svg' %}"/>
            </a>
            <a class="H3" style="margin-top: 0.1rem;">초기화</a>
          </button>
        </div>
        <div class="category_list">
          <div class="category_list_head">
            <a class="H3 text-font1">카테고리</a>
            <a class="reset_btn_2">
              <img class="icon-20 icon-color-2" src="{% static 'assets/icons/up.svg' %}"/>
            </a>
          </div>
          <div class="category_list_content">
            <div class="sidebarnav">
              <label for="skincare"><input type="checkbox" name="category_check_group" id="skincare"/></label>
              <a class="Btn-sidnav text-font1">스킨케어﹒메이크업</a>
              <a class="Caption text-font3">68</a>
            </div>
            <div class="sidebarnav">
              <label for="luxury"><input type="checkbox" name="category_check_group" id="luxury"/></label>
              <a class="Btn-sidnav text-font1">럭셔리뷰티</a>
              <a class="Caption text-font3">24</a>
            </div>
            <div class="sidebarnav">
              <label for="snack"><input type="checkbox" name="category_check_group" id="snack"/></label>
              <a class="Btn-sidnav text-font1">간식﹒과자﹒떡</a>
              <a class="Caption text-font3">28</a>
            </div>
          </div>
        </div>
      </div>
  
      <div class="item">
        <div class="sortingbar">
          <a class="text-font1 H3" id="total_item">총 508건</a>
          <div class="sortingMenu">
            <a class="text-font1 H3">추천순</a>
            <hr class="line"></hr>
            <a class="text-font1 H3">신상품순</a>
            <hr class="line"></hr>
            <a class="text-font1 H3">판매량순</a>
            <hr class="line"></hr>
            <a class="text-font1 H3">혜택순</a>
            <hr class="line"></hr>
            <a class="text-font1 H3">낮은 가격순</a>
            <hr class="line"></hr>
            <a class="text-font1 H3">높은 가격순</a>
          </div>
        </div>
        <div class="category_filter" id="filter" style="display: none;">
          <div class="category_filter_selected">
            <div id="filter_skincare">
              <a class="text-main B2">스킨케어﹒메이크업</a>
              <button id="skincare_btn">
                <img class="icon-20 icon-color-3" src="{% static 'assets/icons/close.svg' %}"/>
              </button>
            </div>
            <div id="filter_luxury">
              <a class="text-main B2" id="filter_luxury">럭셔리뷰티</a>
              <button id="luxury_btn">
                <img class="icon-20 icon-color-3" src="{% static 'assets/icons/close.svg' %}"/>
              </button>
            </div>
            <div id="filter_snack">
              <a class="text-main B2">간식﹒과자﹒떡</a>
              <button id="snack_btn">
                <img class="icon-20 icon-color-3" src="{% static 'assets/icons/close.svg' %}"/>
              </button>
            </div>
          </div>
        </div>
        <div class="itemlist">
          {% for product in products %}
          <div class="productcard" style="width: 15.562rem; /* 249px */;">
            <a href="product/{{product.id}}">
              <img src="{{product.image_url}}" class="rectangle"/>
              <div class="item_select">
                <a>
                  <img class="icon-20 icon-color-4" src="{% static 'assets/icons/cart.svg' %}"/>
                </a>
                <a class="text-font1 Btn">담기</a>
              </div>
              <div class="item_explain">
                <div class="item_explain-1">
                  <a class="text-font2 B2">샛별배송</a>
                </div>
                <div class="item_explain-2">
                  <a class="text-font1 B1 flexing">{{product}}</a>
                </div>
                <div class="item_explain-3">
                  <a class="text-font2 Caption flexing">{{product.description}}</a>
                </div>
                <div class="item_explain-4">
                  <a class="text-font2 decoline">{{product.origin_price}}원</a>
                  <div class="cost">
                    <a class="B1-bold text-red">{{product.discount_rate}}%</a>
                    <a class="text-font1 B1-bold">{{product.discount_price}} 원</a>
                  </div>
                </div>
              </div>
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>



<!-- js 파일 -->
<script src="{% static 'js/main/main_page.js'%}"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const currentPath = window.location.pathname;

    const tag2menu = document.getElementById("tag2");
    const tag2list = tag2menu.children;

    Array.from(tag2list).forEach(function (menu) {
      if (menu.href == "http://127.0.0.1:8000" + currentPath) {
        menu.style.color = "#5e0080";
      }
    });
  });
</script>
{% endblock %}



<!-- 코드 작성시, 아래 부분(script 태그 이전)은 전체 삭제하고 작성하세요 -->

<!----------------tip!---------------->
<!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
<!-- 아래와 같은 형식으로 for문을 사용하여 작성하세요 -->

<!-- 데이터 사용 예시 -->
<!--<div style="display: flex">
  {% for product in products %}
  <a href="product/{{product.id}}">
    <img src="{{product.image_url}}" style="width: 100px" />
    <p>{{product}}</p>
    <p>{{product.description}}</p>
    <p>{{product.origin_price}}원</p>
    <p>{{product.discount_rate}}%</p>
    <p>{{product.discount_price}}원</p>
  </a>
  {% endfor %}
</div>
데이터 사용 예시 -->

FE_3week/main/templates/main/product_detail_page.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/main/product_detail_page.css'%}"
/>

<div class="screen">
  <div class="main">
    <div class="body">
      <div class="product_introduction">
        <img src="{{product.image_url}}" style="width: 26.875rem; /* 430px */ height: 34.375rem; /* 550px */ border-radius: 0.5rem; /* 8px */ background-color: #D9D9D9;" class="rectangle"/>
        <div class="product_introduction_2">
          <div class="introduction">
            <p class="text-font2 H3">셋별배송</p>
            <div class="product_name"><p class="text-font1 TAEJUN">{{product.name}}</p></div>
            <div class="product_discount">
              <p class="text-red TAEJUN_2">{{product.discount_rate}}%</p>
              <p id="product_price" class="text-font1 TAEJUN_2">{{product.discount_price}} 원</p>
            </div>
            <div class="line"></div>
            <div class="product_notice">
              <p class="text-font2 B2-bold" style="width: 8rem; /* 128px */">안내사항</p>
              <p class="text-font1 B2">{{product.notice}}</p>
            </div>
            <div class="line"></div>
            <div class="select_product">
              <p class="text-font2 B2-bold" style="width: 8rem; /* 128px */">상품선택</p>
              <div class="calc_select_product">
                <p class="text-font2 B2">{{product.name}}</p> <!--나중에 배울듯-->
                <div class="select_product_amount">
                  <button id="product_amount_minus_btn" class="text-font1 B2-bold" style="width: 1.25rem; /* 20px */ text-align: center;">-</button>
                  <p class="text-font1 B2-bold" id="product_amount" style="width: 2rem; /* 32px */ text-align: center;">0</p>
                  <button id="product_amount_plus_btn" class="text-font1 B2-bold" style="width: 1.25rem; /* 20px */ text-align: center;">+</button>
                </div>
              </div>
            </div>
            <div class="line"></div>
          </div>
          <div class="charge">
            <div class="final_charge">
              <div class="final_charge_2">
                <p class="B2" style="color: #000000;">총 상품 금액 : </p>
                <p id="final_chargement" class="TAEJUN_2">0 원</p>
              </div>
            </div>
            <button class="register">
              <p class="Btn" style="color: #FFF; text-align: center;">로그인</p>
            </button>
          </div>
        </div>
      </div>

      <div class="product_comment">
        <div class="H1 text-font1" style="padding-bottom: 1.875rem">상품후기</div>
        <form action="create_comment/" method="post" class="product_comment_form">
          {% csrf_token %}
          <select name="star" id="">
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
          </select>
          <div style="display: flex; width: 100%">
            <textarea
              placeholder="상품 후기를 남겨주세요"
              name="content"
              id="comment_textarea"
            ></textarea>
            <button
              disabled
              type="submit"
              id="comment_submit"
              class="monocolor text-white"
            >
              등록
            </button>
          </div>
        </form> 
      </div>
    </div>
  </div>
</div>


<script src="{% static 'js/main/product_detail_page.js'%}"></script>

<div class="screen2">
  <div
    style="
      width: 1050px;
      display: flex;
      flex-direction: column;
      gap: 20px;
      padding: 20px 0px;
    "
  >
    {% for comment in comments %}
    <div
      style="
        display: flex;
        flex-direction: column;
        gap: 16px;
        padding: 20px 8px;
        border-bottom: solid 1px #d9d9d9;
      "
    >
      <div style="display: flex; justify-content: space-between">
        <p>평점:{{comment.star}}</p>
        <a href="{% url 'main:delete_comment' comment.id %}">삭제</a>
      </div>
      <p class="B1">{{comment.content}}</p>
    </div>
    {% endfor%}
  </div>
</div>
{% endblock %}

<input type="text" name="content" />
<input type="submit" value="submit" />


<!-- 코드 작성시, 아래 부분(endblock 이전)은 전체 삭제하고 작성하세요 -->

<!----------------tip!---------------->
<!-- 상품 데이터베이스는 프로젝트에 넣어뒀어요 -->
<!-- 아래와 같은 형식으로 사용하세요 -->

<!-- 데이터 사용 예시 -->
<!--<img src="{{product.image_url}}" style="width: 100px" />
<p>{{product.name}}</p>
<p>{{product.discount_rate}}%</p>
<p>{{product.discount_price}} 원</p>
<p>{{product.notice}}</p>
데이터 사용 예시
-->

FE_3week/project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>컬리 - 마켓컬리/뷰티컬리</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/reset.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/style.css'%}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/base/font.css'%}"
    />
  </head>
  <body>
    <!-- 상단 네브바 -->
    {% include 'shared/_topnav.html' %}
    <!-- 상단 네브바 -->

    <!-- 내용 -->
    {% block content %} {% endblock %}
    <!-- 내용 -->
  </body>
</html>

FE_3week/project/templates/shared/_topnav.html
<!--
최상단 네비게이션을 구현한 topnav 입니다.
3개의 section으로 구분되어있습니다.
-->

<!-- 스타일 css import -->
{% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/shared/topnav.css'%}"
/>

<div class="screen">
  <div class="topnav">
    <!-- 로그인 회원가입 고객센터 -->
    <section class="nav-1 text-font2">
      <div class="div">
        <!-- 로그인을 한 경우 -->
        {% if user.is_authenticated %}
        <p class="Caption">{{user.username}}님 안녕하세요!</p>
        <a class="Caption" href="/accounts/logout/">로그아웃</a>

        <!-- 로그인을 하지 않은 경우 -->
        {% else %}
        <a class="Caption" href="/accounts/signup/">회원가입</a>
        <a class="Caption" href="/accounts/login/">로그인</a>
        {% endif %}

        <div class="Caption">고객센터</div>
      </div>
    </section>

    <!-- 로고 서치바 아이콘들 -->
    <div class="search">
      <a class="logo" href="/">
        <img src="{% static 'assets/logo.svg' %}" />
        <div class="B1-bold text-main">마켓컬리</div>
      </a>

      <form class="search-bar">
        <input class="B2" placeholder="검색어를 입력해주세요" />
        <img
          class="icon-24 icon-main"
          src="{% static 'assets/icons/search.svg' %}"
        />
      </form>

      <div class="iconlist">
        <a>
          <img class="icon-24" src="{% static 'assets/icons/location.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/heart.svg' %}" />
        </a>
        <a>
          <img class="icon-24" src="{% static 'assets/icons/cart.svg' %}" />
        </a>
      </div>
    </div>

    <!-- 카테고리들 -->
    <div class="nav-2 text-font1">
      <button class="category">
        <img class="icon-16" src="{% static 'assets/icons/col-3.svg' %}" />
        <div class="Btn-nav">카테고리</div>
      </button>

      <div class="nav-menu-list Btn-nav" id="nav-menu-list">
        <a href="/"> 신상품 </a>
        <a>베스트</a>
        <a>알뜰쇼핑</a>
        <a>특가/혜택</a>
      </div>

      <a class="right-button B2">
        <div class="text-main">샛별·하루</div>
        <div class="text-font3">배송안내</div>
      </a>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const currentPath = window.location.pathname;

    const navMenu = document.getElementById("nav-menu-list");
    const navMenuList = navMenu.children;

    Array.from(navMenuList).forEach(function (menu) {
      if (menu.href == "http://127.0.0.1:8000" + currentPath) {
        menu.style.color = "#5e0080";
      }
    });

    const searchBarInput = document.querySelector(".search-bar > input");
    searchBarInput.addEventListener("keydown", function (event) {
      if (event.key === "Enter") {
        event.preventDefault();
        const searchTerm = searchBarInput.value;
        alert("검색어: " + searchTerm);
      }
    });
  });
</script>